routes/web.php
<?php

Auth::routes([

	'register' => false

]);

Route::group(['middleware' => 'auth'], function(){

	// DASHBOARD

	Route::redirect('/', 'login');

	Route::get('home', 'HomeController@index')
		->name('home');

	// DATES

	Route::resource('dates', 'DateController');

	Route::get('date-type', 'DateController@type')
		->name('date-type');
	
	Route::resource('dates.visitors', 'DateVisitorController');

	Route::get('get-barcode-date', 'DateVisitorController@get_barcode_date')
		->name('get-barcode-date');

	Route::post('update-date-visitor-status-with-barcode', 'DateVisitorController@update_date_visitor_status_with_barcode')
		->name('update-date-visitor-status-with-barcode');

	Route::resource('dates.vehicles', 'DateVehicleController');

	Route::resource('dates.containers', 'DateContainerController');

	Route::get('get-date/{date}', 'DateController@get_date')
		->name('get-date');
	
	Route::post('dates/{date}/set-new-visitor-from-date', 'DateVisitorController@set_new_visitor_from_date')
		->name('set-new-visitor-from-date');

	Route::get('search-dates', 'DateController@search')
		->name('search-dates');

	Route::post('store-pictures/{visitor}', 'DateVisitorController@store_pictures')
		->name('store-pictures');

	Route::post('add-existing-vehicle-to-date/{date}', 'DateController@add_existing_vehicle')
		->name('add-existing-vehicle-to-date');

	Route::post('add-new-vehicle-to-date/{date}', 'DateController@add_new_vehicle')
		->name('add-new-vehicle-to-date');

	Route::delete('remove-vehicle/{date_vehicle}/from-date/{date}', 'DateController@remove_vehicle')
		->name('remove-vehicle-from-date');

	// COMPANIES, VISITORS, VEHICLES & CONTAINERS

	Route::resource('companies', 'CompanyController');
	
	Route::resource('companies.visitors', 'VisitorController');

	Route::get('companies/{company}/dates', 'CompanyController@dates')
		->name('company-dates');

	Route::resource('companies.vehicles', 'VehicleController');

	Route::get('vehicles', 'VehicleController@all')
		->name('vehicles');

	Route::get('new-vehicle', 'VehicleController@new_vehicle')
		->name('new-vehicle');

	Route::post('store-vehicle', 'VehicleController@store_vehicle')
		->name('store-vehicle');

	Route::get('check-vehicle', 'VehicleController@check_vehicle')
		->name('check-vehicle');

	Route::get('search-vehicle-plates', 'VehicleController@search_vehicle_plates')
		->name('search-vehicle-plates');

	Route::put('update-date-vehicle/{date_vehicle}', 'VehicleController@update_date_vehicle')
		->name('update-date-vehicle');

	Route::delete('remove-date-vehicle-image/{image}', 'VehicleController@remove_date_vehicle_image')
		->name('remove-date-vehicle-image');

	Route::resource('containers', 'ContainerController');

	// INDEPENDENT VISITORS

	Route::get('visitors', 'VisitorController@all')->name('visitors');

	Route::get('new-visitor', 'VisitorController@new_visitor')->name('new-visitor');

	Route::post('store-visitor', 'VisitorController@store_visitor')->name('store-visitor');

	// DEPARTMENTS, HOSTS & DEPARTMENT EMPLOYEES

	Route::resource('departments', 'DepartmentController');

	Route::resource('departments.hosts', 'HostController');

	Route::get('user/{user}/host', 'HostController@get_single_host');

	Route::get('user/{user}/host-dates', 'HostController@get_single_host_with_dates');

	Route::resource('departments.employees', 'EmployeeController');

	Route::get('employees', 'EmployeeController@all')
		->name('employees');

	Route::get('new-employee', 'EmployeeController@new_employee')
		->name('new-employee');

	Route::post('store-employee', 'EmployeeController@store_employee')
		->name('store-employee');

	Route::get('show-employee/{employee}', 'EmployeeController@show_employee')
		->name('show-employee');

	Route::get('edit-employee/{employee}', 'EmployeeController@edit_employee')
		->name('edit-employee');

	Route::put('update-employee/{employee}', 'EmployeeController@update_employee')
		->name('update-employee');

	Route::delete('delete-employee/{employee}', 'EmployeeController@destroy_employee')
		->name('destroy-employee');

	Route::get('departments/{department}/dates', 'DepartmentController@dates')
		->name('department-dates');


	// CALENDAR

	Route::get('calendar', 'CalendarController@index')
		->name('calendar');


	// MEETING ROOMS

	Route::resource('meeting-rooms', 'MeetingRoomController');

	// USERS [ADMIN, TERMINAL]

	Route::resource('users', 'UserController');

	Route::get('user/{user}/unread-notifications', 'UserController@unread_notifications')
		->name('get-unread-notifications');

	Route::get('user/{user}/notifications', 'UserController@notifications');

	// GLOBAL CONFIG

	Route::get('config', 'ConfigController@index')->name('config');

	Route::put('update-config', 'ConfigController@update')->name('update-config');

});

app/Date.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Date extends Model
{

    protected $guarded = [];

    protected $hidden = [
        'status_id',
    ];

    protected $appends = [
        'status',
        'company_name',
        'department_name',
        'host_name',
        'visitors_total',
        'start',
        'end',
    ];

    protected $casts = [

        'start_at' => 'date:d M, Y h:i a',

    ];

    public function histories()
    {

        return $this->hasMany(DateHistory::class, 'date_id');

    }

    public function company()
    {

        return $this->belongsTo(Company::class, 'company_id');

    }

    public function getCompanyNameAttribute()
    {

        return $this->company->name;

    }

    public function visitors()
    {

        return $this->hasMany(DateVisitor::class, 'date_id');

    }

    public function vehicles()
    {

        return $this->hasMany(DateVehicle::class, 'date_id');

    }

    public function getVehiclesTotalAttribute()
    {

        return $this->vehicles()->count();

    }


    public function containers(){

        return $this->hasMany(DateContainer::class)->orderBy('created_at', 'desc');

    }


    public function getVisitorsTotalAttribute()
    {

        return '(' . $this->visitors()->count() . ') Visitantes';

    }

    public function department()
    {

        return $this->belongsTo(Department::class, 'department_id');

    }

    public function getDepartmentNameAttribute()
    {

        return $this->department->name;

    }

    public function host()
    {

        return $this->belongsTo(Host::class, 'host_id');

    }

    public function getHostNameAttribute()
    {

        return $this->host->user->full_name;

    }

    public function getStartAttribute()
    {

        return $this->start_at->format('d M Y - h:i a');

    }

    public function getEndAttribute()
    {

        $start = $this->start_at;

        $vigency = $this->vigency;

        $end = '';

        if ($vigency == 0) {

            $end = Carbon::parse($start)->endOfDay()->format('d M Y - h:i a');

        } else {

            $end = Carbon::parse($start)->addHours($vigency)->format('d M Y - h:i a');

        }

        return $end;

    }

    public function getEndWithoutFormatAttribute()
    {

        $start = $this->start_at;

        $vigency = $this->vigency;

        $end = '';

        if ($vigency == 0) {

            $end = Carbon::parse($start)->endOfDay();

        } else {

            $end = Carbon::parse($start)->addHours($vigency);

        }

        return $end;

    }

    public function getStatusAttribute()
    {

        switch ($this->status_id) {
            case 0:
                return 'En espera';
                break;

            case 1:
                return 'En curso';
                break;

            case 2:
                return 'Finalizada';
                break;

            case 3:
                return 'Cancelada';
                break;
        }

    }

    public function getStatusBadgeAttribute()
    {

        switch ($this->status_id) {
            case 0:
                return '<span class="badge badge-pill w-100 badge-secondary">En espera</span>';
                break;

            case 1:
                return '<span class="badge badge-pill w-100 badge-success">En curso</span>';
                break;

            case 2:
                return '<span class="badge badge-pill w-100 badge-primary">Finalizada</span>';
                break;

            case 3:
                return '<span class="badge badge-pill w-100 badge-danger">Cancelada</span>';
                break;
        }

    }

    public function getIsExpiredAttribute()
    {

        $now = Carbon::now();

        $start = $this->start_at;

        $vigency = $this->vigency;

        $end = '';

        if ($vigency == 0) {

            $end = Carbon::parse($start)->endOfDay();

        } else {

            $end = Carbon::parse($start)->addHours($vigency);

        }

        if ($now->greaterThan($end)) {

            return '<span class="text-danger"><i class="fa fa-times fa-fw fa-sm"></i> Expirada</span>';

        } else {

            return '<span class="text-success"><i class="fa fa-check fa-fw fa-sm"></i> Vigente</span>';

        }

    }

    public function getIsAvailableAttribute()
    {

        $now = Carbon::now();

        $start = $this->start_at;

        $vigency = $this->vigency;

        $end = '';

        if ($vigency == 0) {

            $end = Carbon::parse($start)->endOfDay();

        } else {

            $end = Carbon::parse($start)->addHours($vigency);

        }

        if ($now->greaterThan($end)) {

            return false;

        } else {

            return true;

        }

    }

    public static function format_dates_to_added_to_calendar($dates)
    {

        $formated_dates = [];

        foreach ($dates as $date) {

            info($date->end);

            $item = [

                'title' => $date->subject,
                'start' => Carbon::parse($date->start_at)->format('Y-m-d h:i a'),
                'end'   => Carbon::parse($date->end_without_format)->format('Y-m-d h:i a'),
                'data'  => $date,

            ];

            array_push($formated_dates, $item);

        }

        info($formated_dates);

        return $formated_dates;

    }

}

app/DateVehicleComment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DateVehicleComment extends Model
{
    
	protected $guarded = [];


	public function vehicle(){

		return $this->belongsTo(DateVehicle::class, 'date_vehicle_id');

	}


	public function user(){

		return $this->belongsTo(User::class, 'user_id');

	}


	public function getDateAttribute(){

		return $this->created_at->format('d M, Y h:i a');

	}

	public function getAuthorAttribute(){

		return $this->user->full_name;

	}


}

app/DateVehicleImage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DateVehicleImage extends Model
{
    

	protected $guarded = [];


	public function vehicle(){

		return $this->belongsTo(DateVehicle::class, 'date_vehicle_id');

	}


	public function getPathAttribute(){


		return asset('vehicles-78xtr45/' . $this->pathname);


	}


}

app/Vehicle.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vehicle extends Model
{
    

	protected $guarded = [];

	protected $hidden = [];

	protected $appends = [
		'name'
	];

	public function company(){

		return $this->belongsTo(Company::class, 'company_id');

	}

	public function getCompanyNameAttribute(){

		return $this->company->name;

	}

	public function dates(){

		return $this->hasMany(DateVehicle::class, 'vehicle_id');

	}

	public function getDatesTotalAttribute(){

		return '('.$this->dates()->count().') Citas';

	}

	public function getTypeAttribute(){

		switch ($this->type_id) {
			case 0:
				return 'MICRO';
				break;

			case 1:
				return 'SEDAN';
				break;

			case 2:
				return 'CUV';
				break;

			case 3:
				return 'SUV';
				break;

			case 4:
				return 'HATCHBACK';
				break;
			
			case 5:
				return 'ROADSTER';
				break;

			case 6:
				return 'PICKUP';
				break;

			case 7:
				return 'VAN';
				break;

			case 8:
				return 'COUPE';
				break;

			case 9:
				return 'SUPER-CAR';
				break;

			case 10:
				return 'CAMPER-VAN';
				break;

			case 11:
				return 'MINI-TRUCK';
				break;

			case 12:
				return 'CABRIOLET';
				break;

			case 13:
				return 'MINI-VAN';
				break;

			case 14:
				return 'TRUCK';
				break;

			case 15:
				return 'BIG-TRUCK';
				break;
		}

	}


	public function getNameAttribute(){

		
		return "{$this->brand} - {$this->model} | Año: {$this->year} | Color: {$this->color} | Placas: {$this->plates}";


	}

	public function getShortNameAttribute(){

		return "{$this->brand} {$this->model}";

	}

}

resources/views/app/vehicles/all.blade.php
@extends('layouts.app')

@section('content')

	<div class="container-fluid">
		@include('app.components.vehicles-table', [
			'title' 	=> 'Listado de vehículos',
			'vehicles' 	=> $vehicles
		])
	</div>

@stop

resources/views/app/vehicles/check.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container-fluid">
		
		<div class="card shadow-sm">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">
					<i class="fa fa-car mr-2 text-muted"></i>
					Buscar vehículo
				</p>
			</div>
			<div class="card-body">
				
				<form action="{{ route('search-vehicle-plates') }}" id="searchVehicleForm" method="get">
				
					@csrf

					<div class="form-group row">
						<div class="col-sm-6 offset-0 offset-sm-3">
							<p class="mb-2">Introduce el número de placas del vehículo</p>
							<p class="text-muted m-0">(solo números y letras)</p>
						</div>
					</div>

					<div class="form-group row">
						<label class="col-sm-3 col-form-label text-left text-sm-right">No. placas</label>
						<div class="col-sm-6">
							<input type="text" 
								value="{{ old('plates') }}" 
								name="plates" 
								class="form-control" 
								required>
						</div>
					</div>

				</form>

			</div>
			<div class="card-footer">
				<div class="form-group row mb-0">
					<div class="col-sm-6 offset-0 offset-sm-3">
						<button type="submit" form="searchVehicleForm" class="btn btn-primary">
							<i class="fa fa-search mr-2"></i>
							Buscar
						</button>
					</div>
				</div>
			</div>
		</div>

	</div>

@stop

resources/views/app/vehicles/create.blade.php
@extends('layouts.app')

@section('content')

	<div class="container-fluid">
		
		<div class="card shadow-sm">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">{{ $company->name }} | Nuevo vehículo</p>
			</div>
			<div class="card-body">
				<form action="{{ route('companies.vehicles.store', $company) }}" method="post" id="newVehicleForm">
					
					@include('app.vehicles.partials.form')

				</form>
			</div>
			<div class="card-footer">
				<div class="form-group row mb-0">
					<div class="col-sm-6 offset-3">
						<button type="submit" class="btn btn-primary" form="newVehicleForm">
							<i class="fa fa-check mr-2"></i>
							Guardar
						</button>
					</div>
				</div>
			</div>
		</div>

	</div>

@stop

resources/views/app/vehicles/edit.blade.php
@extends('layouts.app')

@section('content')

	<div class="container-fluid">
		<div class="card shadow-sm">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">Editar vehículo</p>
			</div>
			<div class="card-body">
				
				<form action="{{ route('companies.vehicles.update', [$vehicle->company, $vehicle]) }}" 
					method="post" 
					id="updateVehicleForm">
					
					@method('PATCH')

					@include('app.vehicles.partials.form')

				</form>

			</div>
			<div class="card-footer">
				<div class="form-group row mb-0">
					<div class="col-sm-6 offset-3 d-flex align-items-center">
						<button type="submit" class="btn btn-primary" form="updateVehicleForm">
							<i class="fa fa-check mr-2"></i>
							Actualizar
						</button>
			
						<form action="{{ route('companies.vehicles.destroy', [$company, $vehicle]) }}" method="post" class="ml-2">
							@csrf
							@method('DELETE')
							<button type="submit" 
								class="btn btn-outline-danger"
								onclick="return confirm('¿Estás seguro que deseas eliminar este vehículo?, al hacerlo se eliminará de las citas relacionadas.')">
								<i class="fa fa-trash-alt mr-2"></i>
								Eliminar
							</button>
						</form>

					</div>
				</div>
			</div>
		</div>
	</div>

@stop

resources/views/app/vehicles/index.blade.php
@extends('layouts.app')

@section('content')

	<div class="container-fluid">
		@include('app.components.vehicles-table', [
			'title' 	=> $company->name . '| Listado de vehículos',
			'vehicles' 	=> $vehicles,
			'route' 	=> route('companies.vehicles.create', $company)
		])
	</div>

@stop

resources/views/app/vehicles/new.blade.php
@extends('layouts.app')

@section('content')

	<div class="container-fluid">
		
		<div class="card shadow-sm">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">Nuevo vehículo</p>
			</div>
			<div class="card-body">
				<form action="{{ route('store-vehicle') }}" method="post" id="newVehicleForm">
					
					@include('app.vehicles.partials.form')

				</form>
			</div>
			<div class="card-footer">
				<div class="form-group row mb-0">
					<div class="col-sm-6 offset-3">
						<button type="submit" class="btn btn-primary" form="newVehicleForm">
							<i class="fa fa-check mr-2"></i>
							Guardar
						</button>
					</div>
				</div>
			</div>
		</div>

	</div>

@stop

resources/views/app/vehicles/search-result.blade.php
@extends('layouts.app')
@section('content')

<div class="container-fluid">

	<div class="row">
		<div class="col-sm-6">
			
			<div class="card shadow-sm mt-4 mt-sm-0">
				<div class="card-header d-flex align-items-center">
					<p class="lead m-0">
						<i class="fa fa-car mr-2 text-muted"></i>
						Recepción de vehículos
					</p>
				</div>
				<form action="{{ route('update-date-vehicle', $date_vehicle) }}" 
					class="table-responsive" 
					enctype="multipart/form-data"
					method="post">

					@csrf

					@method('PUT')

					<table class="table m-0 table-striped">
						<tbody>
							<tr>
								<th>Cita:</th>
								<td>
									@component('app.components.back-btn', [
						
										'route' => route('dates.show', $date),
										'text' => 'Regresar a la cita'
		
									])

									@endcomponent
								</td>
							</tr>
							@available($date->is_available)
							<tr>
								<th>Fotografías:</th>
								<td>
									<input type="file" name="images[]" accept="image/*" multiple>
								</td>
							</tr>
							@endavailable
							<tr>
								<th>Vehículo:</th>
								<td>
									<a href="{{ route('companies.vehicles.show', [$vehicle->company, $vehicle]) }}">
										{{ $vehicle->name }}
									</a>
								</td>
							</tr>
							<tr>
								<th>Total de visitantes:</th>
								<td>
									<a href="{{ route('dates.show', $date) }}">{{ $date_vehicle->date->visitors_total }}</a>
								</td>
							</tr>
							<tr>
								<th>Fecha y hora:</th>
								<td>{{ $date->start }}</td>
							</tr>
							<tr>
								<th>Vigencia:</th>
								<td>{{ $date->end }} | {!! $date->is_expired !!}</td>
							</tr>
							<tr>
								<th>Status:</th>
								<td>
									<div class="d-flex">
										<div class="w-50">
											{!! $date_vehicle->status !!}
										</div>
									</div>
								</td>
							</tr>

							@available($date->is_available)

							<tr>
								<th>Modificar status:</th>
								<td>
									<select name="status_id" id="" class="custom-select">
										<option disabled selected value="">Elige una opción</option>
										<option {{ isset($date_vehicle) ? $date_vehicle->status_id == 0 ? 'selected' : '' : '' }} value="0">En espera</option>
										<option {{ isset($date_vehicle) ? $date_vehicle->status_id == 1 ? 'selected' : '' : '' }} value="1">Dentro de las instalaciones</option>
										<option {{ isset($date_vehicle) ? $date_vehicle->status_id == 2 ? 'selected' : '' : '' }} value="2">Fuera de las instalaciones</option>
									</select>
								</td>
							</tr>
							<tr>
								<th>Comentario:</th>
								<td>
									<textarea name="comment" rows="3" class="form-control @error('comment') is-invalid @enderror" placeholder="Escribe un comentario aquí..."></textarea>
								</td>
							</tr>
							<tr>
								<th></th>
								<td>
									<button type="submit" class="btn btn-primary">
										<i class="fa fa-check mr-2"></i>
										Actualizar
									</button>
								</td>
							</tr>
							<tr>
								<th></th>
								<td>
									<button type="submit" 
										class="btn btn-link p-0 text-danger"
										onclick="return confirm('¿Estás seguro que deseas remove este vehículo de la cita?')"
										form="deleteVehicleForm">
										<i class="fa fa-trash-alt mr-2"></i>
										Eliminar vehículo de esta cita
									</a>
								</td>
							</tr>

							@endavailable
						</tbody>
					</table>
				</form>


				<form action="{{ route('remove-vehicle-from-date', [$date_vehicle, $date]) }}" 
					method="post"
					id="deleteVehicleForm">
					@csrf
					@method('DELETE')
				</form>
			</div>
	
			<div class="card shadow-sm mt-4">
				<div class="card-header d-flex align-items-center">
					<p class="lead m-0">
						<i class="fa fa-clipboard-list mr-2 text-muted"></i>
						Eventos
					</p>
				</div>
			
				@if(count($date_vehicle->histories))

				<table class="table m-0">
					<thead>
						<tr>
							<th>Actividad</th>
							<th>Fecha</th>
						</tr>
					</thead>

					<tbody>
						@foreach($date_vehicle->histories as $history)
						<tr>
							<td>{{ $history->description }}</td>
							<td>{{ $history->created_at->format('d M, Y h:i a') }}</td>
						</tr>
						@endforeach
					</tbody>
				</table>

				@else
		
				<div class="card-body">
					No se ha registrado ningun evento.
				</div>

				@endif
			</div>

		</div>

		<div class="col-sm-6">
			<div class="card shadow-sm">
				<div class="card-header d-flex align-items-center">
					<p class="lead m-0">
						<i class="fa fa-image mr-2 text-muted"></i>
						Imagenes
					</p>
				</div>
				<div class="card-body">
					
				@if(count($date_vehicle->images))

					<div class="d-flex flex-wrap">
						@foreach($date_vehicle->images as $key => $image)
						<div class="thumb border mr-2" 
							style="background-image: url('{{ asset($image->path)  }}')"
							data-toggle="modal"
							data-target="#img{{ $key }}">
							
							@available($date->is_available)

							<a href="#" 
								class="remove_icon" 
								title="Eliminar imagen"
								onclick="event.preventDefault(); var confirm = window.confirm('¿Estás seguro que deseas eliminar esta imagen?'); if(confirm){document.getElementById('removeVehicle{{ $key }}').submit();}">
								<i class="fa fa-times"></i>
							</a>

							<form id="removeVehicle{{ $key }}" action="{{ route('remove-date-vehicle-image', $image) }}" method="POST" style="display: none;">
							    @csrf
							    @method('DELETE')
							</form>

							@endavailable
							
						</div>


						<div class="modal fade" 
							id="img{{ $key }}" 
							tabindex="-1" 
							role="dialog" 
							aria-labelledby="img{{ $key }}Label" 
							aria-hidden="true">

							<div class="modal-dialog modal-lg" role="document">
								<div class="modal-content">
									<div class="modal-body">
										<img src="{{ asset($image->path) }}" class="img-fluid" alt="">
									</div>
								</div>
							</div>
							
						</div>
						@endforeach
					</div>
				
				@else

					No se han agregado imagenes.

				@endif

				</div> 
			</div>

			<div class="card shadow-sm mt-4">
				<div class="card-header d-flex align-items-center">
					<p class="lead m-0">
						<i class="fa fa-comments mr-2 text-muted"></i>
						Comentarios
					</p>
				</div>
		

				@if(count($date_vehicle->comments))

				<table class="table m-0">
					<thead>
						<tr>
							<th>Comentario</th>
							<th>Autor</th>
							<th>Fecha</th>
						</tr>
					</thead>

					<tbody>
						@foreach($date_vehicle->comments as $comment)
					
						<tr>
							<td>{{ $comment->comment }}</td>
							<td nowrap>{{ $comment->author }}</td>
							<td nowrap>{{ $comment->date }}</td>
						</tr>

						@endforeach
					</tbody>
				</table>

				@else
			
				<div class="card-body">
					No se han agregado comentarios.
				</div>

				@endif
			</div>
		</div>

	</div>

</div>

@stop

resources/views/app/vehicles/show.blade.php
@extends('layouts.app')

@section('content')

	<div class="container-fluid">
		<div class="card shadow-sm mb-4">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">Información general</p>
				<a href="{{ route('companies.vehicles.edit', [$company, $vehicle]) }}" class="btn btn-primary ml-auto">
					<i class="fa fa-pencil-alt mr-2"></i>
					Editar
				</a>
			</div>
			<table class="table table-striped m-0">
				<tbody>
					<tr>
						<th width="20%">Tipo:</th>
						<td>{{ $vehicle->type }}</td>
					</tr>

					<tr>
						<th>Marca:</th>
						<td>{{ $vehicle->brand }}</td>
					</tr>

					<tr>
						<th>Modelo:</th>
						<td>{{ $vehicle->model }}</td>
					</tr>

					<tr>
						<th>Año:</th>
						<td>{{ $vehicle->year }}</td>
					</tr>

					<tr>
						<th>Placas:</th>
						<td>{{ $vehicle->plates }}</td>
					</tr>

					<tr>
						<th>Color:</th>
						<td>{{ $vehicle->color }}</td>
					</tr>

					<tr>
						<th>Compañía:</th>
						<td>
							<a href="{{ route('companies.show', $vehicle->company) }}">
								{{ $vehicle->company_name }}
							</a>
						</td>
					</tr>

					<tr>
						<th>Total de citas:</th>
						<td>
							{{ $vehicle->dates_total }}
						</td>
					</tr>
				</tbody>
			</table>
		</div>

		@include('app.components.dates-table', [
			
			'dates' => $dates,
			'title' => '('. count($dates) .') Citas',
		
		])
	</div>

@stop