routes/web.php
<?php

Auth::routes([

	'register' => false

]);

Route::group(['middleware' => 'auth'], function(){

	// DASHBOARD

	Route::redirect('/', 'login');

	Route::get('home', 'HomeController@index')
		->name('home');

	// DATES

	Route::resource('dates', 'DateController');

	Route::get('date-type', 'DateController@type')
		->name('date-type');
	
	Route::resource('dates.visitors', 'DateVisitorController');

	Route::get('get-barcode-date', 'DateVisitorController@get_barcode_date')
		->name('get-barcode-date');

	Route::post('update-date-visitor-status-with-barcode', 'DateVisitorController@update_date_visitor_status_with_barcode')
		->name('update-date-visitor-status-with-barcode');

	Route::resource('dates.vehicles', 'DateVehicleController');

	Route::resource('dates.containers', 'DateContainerController');

	Route::get('get-date/{date}', 'DateController@get_date')
		->name('get-date');
	
	Route::post('dates/{date}/set-new-visitor-from-date', 'DateVisitorController@set_new_visitor_from_date')
		->name('set-new-visitor-from-date');

	Route::get('search-dates', 'DateController@search')
		->name('search-dates');

	Route::post('store-pictures/{visitor}', 'DateVisitorController@store_pictures')
		->name('store-pictures');

	Route::post('add-existing-vehicle-to-date/{date}', 'DateController@add_existing_vehicle')
		->name('add-existing-vehicle-to-date');

	Route::post('add-new-vehicle-to-date/{date}', 'DateController@add_new_vehicle')
		->name('add-new-vehicle-to-date');

	Route::delete('remove-vehicle/{date_vehicle}/from-date/{date}', 'DateController@remove_vehicle')
		->name('remove-vehicle-from-date');

	// COMPANIES, VISITORS, VEHICLES & CONTAINERS

	Route::resource('companies', 'CompanyController');
	
	Route::resource('companies.visitors', 'VisitorController');

	Route::get('companies/{company}/dates', 'CompanyController@dates')
		->name('company-dates');

	Route::resource('companies.vehicles', 'VehicleController');

	Route::get('vehicles', 'VehicleController@all')
		->name('vehicles');

	Route::get('new-vehicle', 'VehicleController@new_vehicle')
		->name('new-vehicle');

	Route::post('store-vehicle', 'VehicleController@store_vehicle')
		->name('store-vehicle');

	Route::get('check-vehicle', 'VehicleController@check_vehicle')
		->name('check-vehicle');

	Route::get('search-vehicle-plates', 'VehicleController@search_vehicle_plates')
		->name('search-vehicle-plates');

	Route::put('update-date-vehicle/{date_vehicle}', 'VehicleController@update_date_vehicle')
		->name('update-date-vehicle');

	Route::delete('remove-date-vehicle-image/{image}', 'VehicleController@remove_date_vehicle_image')
		->name('remove-date-vehicle-image');

	Route::resource('containers', 'ContainerController');

	// INDEPENDENT VISITORS

	Route::get('visitors', 'VisitorController@all')->name('visitors');

	Route::get('new-visitor', 'VisitorController@new_visitor')->name('new-visitor');

	Route::post('store-visitor', 'VisitorController@store_visitor')->name('store-visitor');

	// DEPARTMENTS, HOSTS & DEPARTMENT EMPLOYEES

	Route::resource('departments', 'DepartmentController');

	Route::resource('departments.hosts', 'HostController');

	Route::get('user/{user}/host', 'HostController@get_single_host');

	Route::get('user/{user}/host-dates', 'HostController@get_single_host_with_dates');

	Route::resource('departments.employees', 'EmployeeController');

	Route::get('employees', 'EmployeeController@all')
		->name('employees');

	Route::get('new-employee', 'EmployeeController@new_employee')
		->name('new-employee');

	Route::post('store-employee', 'EmployeeController@store_employee')
		->name('store-employee');

	Route::get('show-employee/{employee}', 'EmployeeController@show_employee')
		->name('show-employee');

	Route::get('edit-employee/{employee}', 'EmployeeController@edit_employee')
		->name('edit-employee');

	Route::put('update-employee/{employee}', 'EmployeeController@update_employee')
		->name('update-employee');

	Route::delete('delete-employee/{employee}', 'EmployeeController@destroy_employee')
		->name('destroy-employee');

	Route::get('departments/{department}/dates', 'DepartmentController@dates')
		->name('department-dates');


	// CALENDAR

	Route::get('calendar', 'CalendarController@index')
		->name('calendar');


	// MEETING ROOMS

	Route::resource('meeting-rooms', 'MeetingRoomController');

	// USERS [ADMIN, TERMINAL]

	Route::resource('users', 'UserController');

	Route::get('user/{user}/unread-notifications', 'UserController@unread_notifications')
		->name('get-unread-notifications');

	Route::get('user/{user}/notifications', 'UserController@notifications');

	// GLOBAL CONFIG

	Route::get('config', 'ConfigController@index')->name('config');

	Route::put('update-config', 'ConfigController@update')->name('update-config');

});

app/Host.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Host extends Model
{
    
	protected $guarded = [];

	protected $hidden = [];

	protected $appends = [
		'full_name'
	];

	public function dates(){

		return $this->hasMany(Date::class, 'host_id');

	}

	public function getDatesTotalAttribute(){

		return '('.$this->dates()->count().') Citas';

	}

	public function user(){

		return $this->belongsTo(User::class, 'user_id');

	}

	public function getFullNameAttribute(){

		return $this->user->full_name;

	}

	public function getEmailAttribute(){

		return $this->user->email;

	}

	public function getJobtitleAttribute(){

		return $this->employee ? $this->employee->jobtitle : 'Sin puesto laboral';

	}

	public function employee(){

		return $this->belongsTo(Employee::class, 'employee_id');

	}

	public function getGenderAttribute(){

		return $this->employee->gender;

	}

	public function department(){

		return $this->belongsTo(Department::class, 'department_id');

	}

	public function getDepartmentNameAttribute(){

		return $this->department->name;

	}

}

app/Http/Controllers/HostController.php
<?php

namespace App\Http\Controllers;

use App\Date;
use App\Department;
use App\Employee;
use App\Host;
use App\Http\Requests\HostRequest;
use App\User;
use Faker\Generator as Faker;
use Illuminate\Http\Request;

class HostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Department $department)
    {

        if (request()->ajax()) {

            $hosts = $department->hosts;

            return response()
                ->json($hosts);

        } else {

            $hosts = $department->hosts()->paginate(10);

            return view('app.hosts.index', compact('department', 'hosts'));

        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Department $department)
    {

        return view('app.hosts.create', compact('department'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(HostRequest $request, Department $department)
    {

        if ($request->has('employee_id')) {

            $employee_is_assigned_to_department = $this->validate_if_employee_is_assigned_to_department($request, $department);

            if ($employee_is_assigned_to_department) {

                $already_assigned = $this->validate_if_employee_is_already_host_from_department($request, $department);

                if ($already_assigned) {

                    return redirect()
                        ->back()
                        ->with('info', 'El personal seleccionado ya se encuentra asignado como encargado en el departamento.');

                } else {

                    $employee = Employee::find($request->employee_id);

                    $user = $this->create_a_user_for_new_host($employee);

                    $host = $this->add_new_host_to_department($employee, $user, $department);

                    return redirect()
                        ->route('departments.hosts.index', $department)
                        ->with('msg', "Se ha asignado a {$host->full_name} para administrar el departamento {$department->name}");

                }

            }

        } else {

            $employee = $this->create_new_employee_to_set_a_new_host($request, $department);

            $user = $this->create_a_user_for_new_host($employee);

            $host = $this->add_new_host_to_department($employee, $user, $department);

            return redirect()
                ->route('departments.hosts.index', $department)
                ->with('msg', "Se ha asignado a {$host->full_name} para administrar el departamento {$department->name}");

        }

    }

    public function create_new_employee_to_set_a_new_host($request, $department)
    {

        $employee = Employee::create([
            'department_id' => $department->id,
            'first_name'    => $request->first_name,
            'last_name'     => $request->last_name,
            'email'         => $request->email,
            'jobtitle'      => $request->jobtitle,
            'phone'         => $request->phone,
            'ext'           => $request->ext,
            'mobile'        => $request->mobile,
            'gender_id'     => $request->gender_id,
            'employee_id'   => hexdec(uniqid()),
        ]);

        return $employee;

    }

    public function add_new_host_to_department($employee, $user, $department)
    {

        $host = Host::create([
            'department_id' => $department->id,
            'user_id'       => $user->id,
            'employee_id'   => $employee->id,
        ]);

        return $host;

    }

    public function create_a_user_for_new_host($employee)
    {

        $faker = \Faker\Factory::create();

        $password = $faker->password;

        $user = User::create([

            'first_name' => $employee->first_name,
            'last_name'  => $employee->last_name,
            'email'      => $employee->email,
            'role'       => 'host',
            'password'   => \Hash::make($password),

        ]);

        return $user;

    }

    public function validate_if_employee_is_assigned_to_department($request, $department)
    {

        $employee = $department->employees()->find($request->employee_id);

        return $employee ? true : false;

    }

    public function validate_if_employee_is_already_host_from_department($request, $department)
    {

        $host = $department->hosts()->where('employee_id', $request->employee_id)->first();

        return $host ? true : false;

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Host  $host
     * @return \Illuminate\Http\Response
     */
    public function show(Department $department, Host $host)
    {

        $dates = $host->dates()->paginate(10);

        return view('app.hosts.show', compact('department', 'host', 'dates'));

    }


    public function get_single_host(User $user){

        if($user->host){

            return response()->json($user->host);

        }

    }

    public function get_single_host_with_dates(User $user){

        if($user->host){

            $response = [

                'user' => $user,
                'host' => $user->host,
                'dates' => Date::format_dates_to_added_to_calendar($user->host->dates),

            ];

            return response()->json($response);

        }

    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Host  $host
     * @return \Illuminate\Http\Response
     */
    public function edit(Department $department, Host $host)
    {

        return view('app.hosts.edit', compact('department', 'host'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Host  $host
     * @return \Illuminate\Http\Response
     */
    public function update(HostRequest $request, Department $department, Host $host)
    {

        $this->update_employee_data($request, $department, $host);

        $this->update_user_data($request, $department, $host);

        return redirect()
            ->route('departments.hosts.show', [$department, $host])
            ->with("msg", "La información del personal ha sido modificada exitosamente.");

    }

    public function update_employee_data($request, $department, $host)
    {

        $employee = $host->employee;

        $employee->update([

            'first_name' => $request->first_name,
            'last_name'  => $request->last_name,
            'email'      => $request->email,
            'jobtitle'   => $request->jobtitle,
            'phone'      => $request->phone,
            'ext'        => $request->ext,
            'mobile'     => $request->mobile,
            'gender_id'  => $request->gender_id,

        ]);

    }

    public function update_user_data($request, $department, $host)
    {

        $user = $host->user;

        $user->update([

            'first_name' => $request->first_name,
            'last_name'  => $request->last_name,
            'email'      => $request->email,

        ]);

        if ($request->password) {

            $user->update([

                'password' => \Hash::make($request->password),

            ]);

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Host  $host
     * @return \Illuminate\Http\Response
     */
    public function destroy(Department $department, Host $host)
    {
        
        if(count($host->dates)){

            $host->dates()->each(function($date){
                $date->visitors()->delete();
            });

            $host->dates()->delete();

        }

        $host->user->delete();

        $host->delete();

        return redirect()
            ->route('departments.hosts.index', $department)
            ->with('warning', "Se ha eliminado al encargado del departamento exitosamente.");

    }
}

resources/views/app/hosts/create.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container-fluid">
		<div class="card shadow-sm">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">{{ $department->name }} | Nuevo encargado de departamento</p>
			</div>

			@if($department->employees()->count())

			<div class="card-body border-bottom bg-light">
				
				<div class="form-group row">
					<div class="col-sm-6 offset-3">

						<p class="mb-3">Selecciona a uno de los empleados asignados a este departamento</p>
						
						<form action="{{ route('departments.hosts.store', $department) }}" method="post" class="d-flex align-items-center">
							
							@csrf

							<select name="employee_id" id="" class="custom-select @error('employee_id') is-invalid @enderror">
								
								<option disabled selected value="">Elige una opción</option>

								@foreach($department->employees as $employee)
								
								<option value="{{ $employee->id }}">{{ $employee->full_name }}</option>

								@endforeach

							</select>

							<button type="submit" 
								class="btn btn-primary ml-2 nowrap">
								
								<i class="fa fa-check mr-2"></i>
								
								Establecer como encargado

							</button>

						</form>

					</div>
				</div>

			</div>

			@endif

			<div class="card-body">
				
				<form action="{{ route('departments.hosts.store', $department) }}" id="newHostForm" method="post">

					@if($department->employees()->count())

					<div class="form-group row mb-0">
						<div class="col-sm-6 offset-3">
							<p class="lead">Ó bien crea uno nuevo</p>
						</div>
					</div>

					@endif

					@include('app.hosts.partials.form')

				</form>

			</div>

			<div class="card-footer pb-0">
				<div class="form-group row">
					<div class="col-sm-6 offset-3">
						<button type="submit" class="btn btn-primary" form="newHostForm">
							<i class="fa fa-check mr-2"></i>
							Guardar
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>

@stop

resources/views/app/hosts/edit.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container-fluid">
		<div class="card shadow-sm">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">Editar información</p>
			</div>
			<div class="card-body">
				
				<form action="{{ route('departments.hosts.update', [$department, $host]) }}" method="post" id="updateHostForm">
					
					@method('PATCH')

					@include('app.hosts.partials.form')

				</form>

			</div>
			<div class="card-footer pb-0">
				<div class="form-group row">
					<div class="col-sm-6 offset-3 d-flex align-items-center">
						<button type="submit" class="btn btn-primary" form="updateHostForm">
							<i class="fa fa-check mr-2"></i>
							Actualizar
						</button>
				
						<form action="{{ route('departments.hosts.destroy', [$department, $host]) }}" method="post" class="ml-2">
							@csrf
							@method('DELETE')
							<button class="btn btn-outline-danger"
								onclick="return confirm('¿Estás seguro que deseas eliminar al encargado del departamento?, al hacerlo se eliminarán sus citas relacionadas.')">
								<i class="fa fa-trash-alt mr-2"></i>
								Eliminar
							</button>
						</form>

					</div>
				</div>
			</div>
		</div>
	</div>

@stop

resources/views/app/hosts/index.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container-fluid">
		
		<div class="card shadow-sm">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">{{ $department->name }} | Encargados</p>
				<a href="{{ route('departments.hosts.create', $department) }}" class="btn btn-primary ml-auto">
					<i class="fa fa-plus mr-2"></i>
					Nuevo
				</a>
			</div>
			
			@if(count($hosts))
				
			<table class="table table-striped m-0">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Correo electrónico</th>
						<th>Puesto laboral</th>
						<th>Total de citas</th>
						<th class="text-right">Detalles</th>
					</tr>
				</thead>

				<tbody>
					@foreach($hosts as $host)

					<tr>
						<td>
							<a href="{{ route('departments.hosts.show', [$department, $host]) }}">
								{{ $host->full_name }}
							</a>
						</td>
						<td>{{ $host->email }}</td>
						<td>{{ $host->jobtitle }}</td>
						<td>{{ $host->dates_total }}</td>
						<td class="text-right">
							<a href="{{ route('departments.hosts.show', [$department, $host]) }}">
								Ver más
							</a>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>

			@else

			<div class="card-body">
				<div class="row">
					<div class="col-sm-4 mx-auto text-center">
						<img src="{{ asset('img/undraw_business_deal_cpi9.svg') }}" class="svg_img w-50 mb-4" alt="">
						<p class="lead">No se han agregado encargados en este departamento aún.</p>
						<a href="{{ route('departments.hosts.create', $department) }}" class="btn btn-primary">
							<i class="fa fa-plus mr-2"></i> 
							Agrega uno
						</a>
					</div>
				</div>
			</div>
	
			@endif

			@if($hosts->total() > $hosts->perPage())
	
			<div class="card-footer">
				{{ $hosts->links() }}
			</div>

			@endif
		</div>

	</div>

@stop

resources/views/app/hosts/show.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container-fluid">
		<div class="card shadow-sm mb-4">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">Información general</p>
				<a href="{{ route('departments.hosts.edit', [$department, $host]) }}" class="btn btn-primary ml-auto">
					<i class="fa fa-pencil-alt mr-2"></i>
					Editar
				</a>
			</div>
			<table class="table table-striped m-0">
				<tbody>
					<tr>
						<th width="20%">Nombre:</th>
						<td>{{ $host->full_name }}</td>
					</tr>

					<tr>
						<th width="20%">Email:</th>
						<td>{{ $host->email }}</td>
					</tr>

					<tr>
						<th width="20%">Género:</th>
						<td>{{ $host->gender }}</td>
					</tr>

					<tr>
						<th width="20%">Puesto laboral:</th>
						<td>{{ $host->jobtitle }}</td>
					</tr>

					<tr>
						<th width="20%">Departamento:</th>
						<td>{{ $host->department_name }}</td>
					</tr>
				</tbody>
			</table>
		</div>

		@include('app.components.dates-table', [
			'dates' => $dates,
			'title' => '('. $dates->total() .') Citas de ' . $host->full_name,
			'route' => route('dates.create') . '?department_id=' . $host->department_id . '&host_id=' . $host->id
		])
	</div>

@stop