routes/web.php
<?php

Auth::routes([

	'register' => false

]);

Route::group(['middleware' => 'auth'], function(){

	// DASHBOARD

	Route::redirect('/', 'login');

	Route::get('home', 'HomeController@index')
		->name('home');

	// DATES

	Route::resource('dates', 'DateController');

	Route::get('date-type', 'DateController@type')
		->name('date-type');
	
	Route::resource('dates.visitors', 'DateVisitorController');

	Route::get('get-barcode-date', 'DateVisitorController@get_barcode_date')
		->name('get-barcode-date');

	Route::post('update-date-visitor-status-with-barcode', 'DateVisitorController@update_date_visitor_status_with_barcode')
		->name('update-date-visitor-status-with-barcode');

	Route::resource('dates.vehicles', 'DateVehicleController');

	Route::resource('dates.containers', 'DateContainerController');

	Route::get('get-date/{date}', 'DateController@get_date')
		->name('get-date');
	
	Route::post('dates/{date}/set-new-visitor-from-date', 'DateVisitorController@set_new_visitor_from_date')
		->name('set-new-visitor-from-date');

	Route::get('search-dates', 'DateController@search')
		->name('search-dates');

	Route::post('store-pictures/{visitor}', 'DateVisitorController@store_pictures')
		->name('store-pictures');

	Route::post('add-existing-vehicle-to-date/{date}', 'DateController@add_existing_vehicle')
		->name('add-existing-vehicle-to-date');

	Route::post('add-new-vehicle-to-date/{date}', 'DateController@add_new_vehicle')
		->name('add-new-vehicle-to-date');

	Route::delete('remove-vehicle/{date_vehicle}/from-date/{date}', 'DateController@remove_vehicle')
		->name('remove-vehicle-from-date');

	// COMPANIES, VISITORS, VEHICLES & CONTAINERS

	Route::resource('companies', 'CompanyController');
	
	Route::resource('companies.visitors', 'VisitorController');

	Route::get('companies/{company}/dates', 'CompanyController@dates')
		->name('company-dates');

	Route::resource('companies.vehicles', 'VehicleController');

	Route::get('vehicles', 'VehicleController@all')
		->name('vehicles');

	Route::get('new-vehicle', 'VehicleController@new_vehicle')
		->name('new-vehicle');

	Route::post('store-vehicle', 'VehicleController@store_vehicle')
		->name('store-vehicle');

	Route::get('check-vehicle', 'VehicleController@check_vehicle')
		->name('check-vehicle');

	Route::get('search-vehicle-plates', 'VehicleController@search_vehicle_plates')
		->name('search-vehicle-plates');

	Route::put('update-date-vehicle/{date_vehicle}', 'VehicleController@update_date_vehicle')
		->name('update-date-vehicle');

	Route::delete('remove-date-vehicle-image/{image}', 'VehicleController@remove_date_vehicle_image')
		->name('remove-date-vehicle-image');

	Route::resource('containers', 'ContainerController');

	// INDEPENDENT VISITORS

	Route::get('visitors', 'VisitorController@all')->name('visitors');

	Route::get('new-visitor', 'VisitorController@new_visitor')->name('new-visitor');

	Route::post('store-visitor', 'VisitorController@store_visitor')->name('store-visitor');

	// DEPARTMENTS, HOSTS & DEPARTMENT EMPLOYEES

	Route::resource('departments', 'DepartmentController');

	Route::resource('departments.hosts', 'HostController');

	Route::get('user/{user}/host', 'HostController@get_single_host');

	Route::get('user/{user}/host-dates', 'HostController@get_single_host_with_dates');

	Route::resource('departments.employees', 'EmployeeController');

	Route::get('employees', 'EmployeeController@all')
		->name('employees');

	Route::get('new-employee', 'EmployeeController@new_employee')
		->name('new-employee');

	Route::post('store-employee', 'EmployeeController@store_employee')
		->name('store-employee');

	Route::get('show-employee/{employee}', 'EmployeeController@show_employee')
		->name('show-employee');

	Route::get('edit-employee/{employee}', 'EmployeeController@edit_employee')
		->name('edit-employee');

	Route::put('update-employee/{employee}', 'EmployeeController@update_employee')
		->name('update-employee');

	Route::delete('delete-employee/{employee}', 'EmployeeController@destroy_employee')
		->name('destroy-employee');

	Route::get('departments/{department}/dates', 'DepartmentController@dates')
		->name('department-dates');


	// CALENDAR

	Route::get('calendar', 'CalendarController@index')
		->name('calendar');


	// MEETING ROOMS

	Route::resource('meeting-rooms', 'MeetingRoomController');

	// USERS [ADMIN, TERMINAL]

	Route::resource('users', 'UserController');

	Route::get('user/{user}/unread-notifications', 'UserController@unread_notifications')
		->name('get-unread-notifications');

	Route::get('user/{user}/notifications', 'UserController@notifications');

	// GLOBAL CONFIG

	Route::get('config', 'ConfigController@index')->name('config');

	Route::put('update-config', 'ConfigController@update')->name('update-config');

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function getFullNameAttribute(){

        return $this->first_name .' '. $this->last_name;

    }


    public function host(){

        return $this->hasOne(Host::class, 'user_id');

    }

    public function getRoleNameAttribute(){

        switch ($this->role) {
            case 'admin':
                return 'Administrador';
                break;

            case 'terminal':
                return 'Terminal';
                break;

            case 'guard':
                return 'Caseta';
                break;

            case 'host':
                return 'Encargado de departamento';
                break;
        }

    }


    public function routeNotificationForNexmo($notification)
    {
        return '+526643864368';
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{

    public function __construct(){

        $this->middleware('notifications-owner')
            ->only('unread_notifications', 'notifications');

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = User::where('role', '<>', 'host')
            ->orderBy('role')
            ->orderBy('first_name')
            ->paginate();

        return view('app.users.index', compact('users'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('app.users.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {

        $user = User::create([

            'first_name' => $request->first_name,
            'last_name'  => $request->last_name,
            'email'      => $request->email,
            'role'       => $request->role,
            'password'   => \Hash::make($request->password),

        ]);

        return redirect()
            ->route('users.show', $user)
            ->with('msg', "Se ha creado el usuario ({$user->full_name}) exitosamente");

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {

        if ($user->role == 'host') {

            return abort(404);

        }

        return view('app.users.show', compact('user'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {

        if ($user->role == 'host') {

            return abort(404);

        }

        return view('app.users.edit', compact('user'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user)
    {

        $can_i_change_role = $this->validate_if_there_is_more_than_one_admin($request, $user);

        if ($can_i_change_role) {

            $user->update([

                'first_name' => $request->first_name,
                'last_name'  => $request->last_name,
                'email'      => $request->email,
                'role'       => $request->role,

            ]);

            if ($request->password) {

                $user->update([

                    'password' => \Hash::make($request->password),

                ]);

            }

            return redirect()
                ->route('users.show', $user)
                ->with('msg', "La información del usuario ha sido actualizada");

        } else {

            return redirect()
                ->back()
                ->withErrors(['No puedes modificar el role del usuario porque es el único administrador en el sistema.']);

        }

    }

    public function validate_if_there_is_more_than_one_admin($request, $user)
    {

        if ($user->role == 'admin' && $request->role == 'terminal') {

            $admin_count = User::where('role', 'admin')->count();

            return $admin_count > 1 ? true : false;

        } else {

            return true;

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {

        $name = $user->full_name;

        $can_i_delete_user = $this->validate_if_i_can_delete_user($user);

        if ($can_i_delete_user) {

            if ($user->host) {

                $user->host->delete();

            }

            $user->delete();

            return redirect()
                ->route('users.index')
                ->with('warning', "Se ha eliminado a {$name} del sistema.");

        } else {

            return redirect()
                ->back()
                ->withErrors(['No puedes eliminar a este usuario ya que es el único administrador en el sistema.']);

        }

    }

    public function validate_if_i_can_delete_user($user)
    {

        if ($user->role == 'admin') {

            $admin_count = User::where('role', 'admin')->count();

            return $admin_count > 1 ? true : false;

        } else {

            return true;

        }

    }

    public function unread_notifications(User $user){

        $notifications = $user->unreadNotifications;
        
        return response()->json($notifications);   

    }

    public function notifications(User $user){

        $notifications = $user->notifications;

        foreach ($user->unreadNotifications as $notification) {
            $notification->markAsRead();
        }

        return view('app.users.notifications', compact('notifications'));

    }

}

resources/views/app/users/create.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container-fluid">
		<div class="card shadow-sm">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">Nuevo usuario</p>
			</div>
			<div class="card-body">
				
				<form action="{{ route('users.store') }}" method="post" id="newUserForm">
					
					@csrf

					@include('app.users.partials.form', ['new' => true])

				</form>

			</div>
			<div class="card-footer">
				
				<div class="row">
					<div class="col-sm-6 offset-3">
						<button type="submit" class="btn btn-primary" form="newUserForm">
							<i class="fa fa-check mr-2"></i>
							Guardar
						</button>
					</div>
				</div>

			</div>
		</div>
	</div>

@stop

resources/views/app/users/edit.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container-fluid">
		<div class="card shadow-sm">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">Editar usuario</p>
			</div>
			<div class="card-body">
				
				<form action="{{ route('users.update', $user) }}" method="post" id="updateUserForm">
					
					@method('PATCH')

					@include('app.users.partials.form')

				</form>

			</div>
			<div class="card-footer">
				<div class="row">
					<div class="col-sm-6 offset-3 d-flex align-items-center">
						<button type="submit" class="btn btn-primary" form="updateUserForm">
							<i class="fa fa-check mr-2"></i>
							Actualizar
						</button>

						<form action="{{ route('users.destroy', $user) }}" method="post" class="ml-2">
							@csrf
							@method('DELETE')
							<button class="btn btn-outline-danger" onclick="return confirm('¿Estás seguro que deseas eliminar a este usuario?')">
								<i class="fa fa-trash-alt mr-2"></i>
								Eliminar
							</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

@stop

resources/views/app/users/index.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container-fluid">
		<div class="card shadow-sm">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">Listado de usuarios</p>
				<a href="{{ route('users.create') }}" class="btn btn-primary ml-auto">
					<i class="fa fa-plus mr-2"></i>
					Nuevo
				</a>
			</div>
			
			@if(count($users))
				
			<table class="table table-striped m-0">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Correo electrónico</th>
						<th>Role</th>
						<th class="text-right">Detalles</th>
					</tr>
				</thead>

				<tbody>
					@foreach($users as $user)
					<tr>
						<td>
							<a href="{{ route('users.show', $user) }}">
								{{ $user->full_name }}
							</a>
						</td>
						<td>{{ $user->email }}</td>
						<td>{{ $user->role_name }}</td>
						<td class="text-right">
							<a href="{{ route('users.show', $user) }}">
								Ver más
							</a>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>

			@else

			<div class="card-body">
				<div class="row">
					<div class="col-sm-4 mx-auto text-center">
						<img src="{{ asset('img/undraw_programmer_imem.svg') }}" class="svg_img w-50 mb-4" alt="">
						<p class="lead">No se han agregado usuarios aún.</p>
						<a href="{{ route('users.create') }}" class="btn btn-primary">
							<i class="fa fa-plus mr-2"></i> 
							Agrega uno
						</a>
					</div>
				</div>
			</div>

			@endif
			
			@if($users->total() > $users->perPage())
			<div class="card-footer">
				{{ $users->links() }}
			</div>
			@endif
		</div>
	</div>

@stop

resources/views/app/users/notifications.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container-fluid">
		
		<div class="card shadow-sm">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">Notificaciones</p>
			</div>

			<div class="list-group list-group-flush">
				@foreach($notifications as $notification)
				<li class="list-group-item">
					
					@if($notification->type == 'App\Notifications\NotifyToHostWhenVisitorIsArriving')

						{{ $notification->data['msg'] }}

					@else

					@endif

				</li>
				@endforeach
			</div>
		</div>

	</div>

@stop

resources/views/app/users/show.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container-fluid">
		<div class="card shadow-sm">
			<div class="card-header d-flex align-items-center">
				<p class="lead m-0">Información general</p>
				<a href="{{ route('users.edit', $user) }}" class="btn btn-primary ml-auto">
					<i class="fa fa-pencil-alt mr-2"></i>
					Editar
				</a>
			</div>
			<table class="table table-striped m-0">
				<tbody>
					<tr>
						<th width="20%">Nombre(s):</th>
						<td>{{ $user->first_name }}</td>
					</tr>
					<tr>
						<th>Apellido(s):</th>
						<td>{{ $user->last_name }}</td>
					</tr>
					<tr>
						<th>Correo electrónico:</th>
						<td>{{ $user->email }}</td>
					</tr>
					<tr>
						<th>Role:</th>
						<td>{{ $user->role_name }}</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>

@stop