routes/web.php
<?php

Auth::routes([

	'register' => false

]);

Route::group(['middleware' => 'auth'], function(){

	// DASHBOARD

	Route::redirect('/', 'login');

	Route::get('home', 'HomeController@index')
		->name('home');

	// DATES

	Route::resource('dates', 'DateController');

	Route::get('date-type', 'DateController@type')
		->name('date-type');
	
	Route::resource('dates.visitors', 'DateVisitorController');

	Route::get('get-barcode-date', 'DateVisitorController@get_barcode_date')
		->name('get-barcode-date');

	Route::post('update-date-visitor-status-with-barcode', 'DateVisitorController@update_date_visitor_status_with_barcode')
		->name('update-date-visitor-status-with-barcode');

	Route::resource('dates.vehicles', 'DateVehicleController');

	Route::resource('dates.containers', 'DateContainerController');

	Route::get('get-date/{date}', 'DateController@get_date')
		->name('get-date');
	
	Route::post('dates/{date}/set-new-visitor-from-date', 'DateVisitorController@set_new_visitor_from_date')
		->name('set-new-visitor-from-date');

	Route::get('search-dates', 'DateController@search')
		->name('search-dates');

	Route::post('store-pictures/{visitor}', 'DateVisitorController@store_pictures')
		->name('store-pictures');

	Route::post('add-existing-vehicle-to-date/{date}', 'DateController@add_existing_vehicle')
		->name('add-existing-vehicle-to-date');

	Route::post('add-new-vehicle-to-date/{date}', 'DateController@add_new_vehicle')
		->name('add-new-vehicle-to-date');

	Route::delete('remove-vehicle/{date_vehicle}/from-date/{date}', 'DateController@remove_vehicle')
		->name('remove-vehicle-from-date');

	// COMPANIES, VISITORS, VEHICLES & CONTAINERS

	Route::resource('companies', 'CompanyController');
	
	Route::resource('companies.visitors', 'VisitorController');

	Route::get('companies/{company}/dates', 'CompanyController@dates')
		->name('company-dates');

	Route::resource('companies.vehicles', 'VehicleController');

	Route::get('vehicles', 'VehicleController@all')
		->name('vehicles');

	Route::get('new-vehicle', 'VehicleController@new_vehicle')
		->name('new-vehicle');

	Route::post('store-vehicle', 'VehicleController@store_vehicle')
		->name('store-vehicle');

	Route::get('check-vehicle', 'VehicleController@check_vehicle')
		->name('check-vehicle');

	Route::get('search-vehicle-plates', 'VehicleController@search_vehicle_plates')
		->name('search-vehicle-plates');

	Route::put('update-date-vehicle/{date_vehicle}', 'VehicleController@update_date_vehicle')
		->name('update-date-vehicle');

	Route::delete('remove-date-vehicle-image/{image}', 'VehicleController@remove_date_vehicle_image')
		->name('remove-date-vehicle-image');

	Route::resource('containers', 'ContainerController');

	// INDEPENDENT VISITORS

	Route::get('visitors', 'VisitorController@all')->name('visitors');

	Route::get('new-visitor', 'VisitorController@new_visitor')->name('new-visitor');

	Route::post('store-visitor', 'VisitorController@store_visitor')->name('store-visitor');

	// DEPARTMENTS, HOSTS & DEPARTMENT EMPLOYEES

	Route::resource('departments', 'DepartmentController');

	Route::resource('departments.hosts', 'HostController');

	Route::get('user/{user}/host', 'HostController@get_single_host');

	Route::get('user/{user}/host-dates', 'HostController@get_single_host_with_dates');

	Route::resource('departments.employees', 'EmployeeController');

	Route::get('employees', 'EmployeeController@all')
		->name('employees');

	Route::get('new-employee', 'EmployeeController@new_employee')
		->name('new-employee');

	Route::post('store-employee', 'EmployeeController@store_employee')
		->name('store-employee');

	Route::get('show-employee/{employee}', 'EmployeeController@show_employee')
		->name('show-employee');

	Route::get('edit-employee/{employee}', 'EmployeeController@edit_employee')
		->name('edit-employee');

	Route::put('update-employee/{employee}', 'EmployeeController@update_employee')
		->name('update-employee');

	Route::delete('delete-employee/{employee}', 'EmployeeController@destroy_employee')
		->name('destroy-employee');

	Route::get('departments/{department}/dates', 'DepartmentController@dates')
		->name('department-dates');


	// CALENDAR

	Route::get('calendar', 'CalendarController@index')
		->name('calendar');


	// MEETING ROOMS

	Route::resource('meeting-rooms', 'MeetingRoomController');

	// USERS [ADMIN, TERMINAL]

	Route::resource('users', 'UserController');

	Route::get('user/{user}/unread-notifications', 'UserController@unread_notifications')
		->name('get-unread-notifications');

	Route::get('user/{user}/notifications', 'UserController@notifications');

	// GLOBAL CONFIG

	Route::get('config', 'ConfigController@index')->name('config');

	Route::put('update-config', 'ConfigController@update')->name('update-config');

});

app/Date.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Date extends Model
{

    protected $guarded = [];

    protected $hidden = [
        'status_id',
    ];

    protected $appends = [
        'status',
        'company_name',
        'department_name',
        'host_name',
        'visitors_total',
        'start',
        'end',
    ];

    protected $casts = [

        'start_at' => 'date:d M, Y h:i a',

    ];

    public function histories()
    {

        return $this->hasMany(DateHistory::class, 'date_id');

    }

    public function company()
    {

        return $this->belongsTo(Company::class, 'company_id');

    }

    public function getCompanyNameAttribute()
    {

        return $this->company->name;

    }

    public function visitors()
    {

        return $this->hasMany(DateVisitor::class, 'date_id');

    }

    public function vehicles()
    {

        return $this->hasMany(DateVehicle::class, 'date_id');

    }

    public function getVehiclesTotalAttribute()
    {

        return $this->vehicles()->count();

    }


    public function containers(){

        return $this->hasMany(DateContainer::class)->orderBy('created_at', 'desc');

    }


    public function getVisitorsTotalAttribute()
    {

        return '(' . $this->visitors()->count() . ') Visitantes';

    }

    public function department()
    {

        return $this->belongsTo(Department::class, 'department_id');

    }

    public function getDepartmentNameAttribute()
    {

        return $this->department->name;

    }

    public function host()
    {

        return $this->belongsTo(Host::class, 'host_id');

    }

    public function getHostNameAttribute()
    {

        return $this->host->user->full_name;

    }

    public function getStartAttribute()
    {

        return $this->start_at->format('d M Y - h:i a');

    }

    public function getEndAttribute()
    {

        $start = $this->start_at;

        $vigency = $this->vigency;

        $end = '';

        if ($vigency == 0) {

            $end = Carbon::parse($start)->endOfDay()->format('d M Y - h:i a');

        } else {

            $end = Carbon::parse($start)->addHours($vigency)->format('d M Y - h:i a');

        }

        return $end;

    }

    public function getEndWithoutFormatAttribute()
    {

        $start = $this->start_at;

        $vigency = $this->vigency;

        $end = '';

        if ($vigency == 0) {

            $end = Carbon::parse($start)->endOfDay();

        } else {

            $end = Carbon::parse($start)->addHours($vigency);

        }

        return $end;

    }

    public function getStatusAttribute()
    {

        switch ($this->status_id) {
            case 0:
                return 'En espera';
                break;

            case 1:
                return 'En curso';
                break;

            case 2:
                return 'Finalizada';
                break;

            case 3:
                return 'Cancelada';
                break;
        }

    }

    public function getStatusBadgeAttribute()
    {

        switch ($this->status_id) {
            case 0:
                return '<span class="badge badge-pill w-100 badge-secondary">En espera</span>';
                break;

            case 1:
                return '<span class="badge badge-pill w-100 badge-success">En curso</span>';
                break;

            case 2:
                return '<span class="badge badge-pill w-100 badge-primary">Finalizada</span>';
                break;

            case 3:
                return '<span class="badge badge-pill w-100 badge-danger">Cancelada</span>';
                break;
        }

    }

    public function getIsExpiredAttribute()
    {

        $now = Carbon::now();

        $start = $this->start_at;

        $vigency = $this->vigency;

        $end = '';

        if ($vigency == 0) {

            $end = Carbon::parse($start)->endOfDay();

        } else {

            $end = Carbon::parse($start)->addHours($vigency);

        }

        if ($now->greaterThan($end)) {

            return '<span class="text-danger"><i class="fa fa-times fa-fw fa-sm"></i> Expirada</span>';

        } else {

            return '<span class="text-success"><i class="fa fa-check fa-fw fa-sm"></i> Vigente</span>';

        }

    }

    public function getIsAvailableAttribute()
    {

        $now = Carbon::now();

        $start = $this->start_at;

        $vigency = $this->vigency;

        $end = '';

        if ($vigency == 0) {

            $end = Carbon::parse($start)->endOfDay();

        } else {

            $end = Carbon::parse($start)->addHours($vigency);

        }

        if ($now->greaterThan($end)) {

            return false;

        } else {

            return true;

        }

    }

    public static function format_dates_to_added_to_calendar($dates)
    {

        $formated_dates = [];

        foreach ($dates as $date) {

            info($date->end);

            $item = [

                'title' => $date->subject,
                'start' => Carbon::parse($date->start_at)->format('Y-m-d h:i a'),
                'end'   => Carbon::parse($date->end_without_format)->format('Y-m-d h:i a'),
                'data'  => $date,

            ];

            array_push($formated_dates, $item);

        }

        info($formated_dates);

        return $formated_dates;

    }

}

app/Host.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Host extends Model
{
    
	protected $guarded = [];

	protected $hidden = [];

	protected $appends = [
		'full_name'
	];

	public function dates(){

		return $this->hasMany(Date::class, 'host_id');

	}

	public function getDatesTotalAttribute(){

		return '('.$this->dates()->count().') Citas';

	}

	public function user(){

		return $this->belongsTo(User::class, 'user_id');

	}

	public function getFullNameAttribute(){

		return $this->user->full_name;

	}

	public function getEmailAttribute(){

		return $this->user->email;

	}

	public function getJobtitleAttribute(){

		return $this->employee ? $this->employee->jobtitle : 'Sin puesto laboral';

	}

	public function employee(){

		return $this->belongsTo(Employee::class, 'employee_id');

	}

	public function getGenderAttribute(){

		return $this->employee->gender;

	}

	public function department(){

		return $this->belongsTo(Department::class, 'department_id');

	}

	public function getDepartmentNameAttribute(){

		return $this->department->name;

	}

}

resources/views/app/components/alerts.blade.php
<div class="container-fluid">
	
	@if ($errors->any())
	    <div class="alert alert-danger alert-dismissible fade show" role="alert">
	      
			@foreach ($errors->all() as $error)
			    
			    <p class="m-0">{{ $error }}</p>

			@endforeach

			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				
				<span aria-hidden="true">&times;</span>

			</button>
	    </div>
	@endif


	@if (session('msg'))
	    <div class="alert alert-success alert-dismissible fade show" role="alert">
	        
	        {{ session('msg') }}

	        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	        	
	        	<span aria-hidden="true">&times;</span>

	        </button>

	    </div>
	@endif

	@if (request('new_date'))
	    <div class="alert alert-success alert-dismissible fade show" role="alert">
	        
	        Se ha creado una nueva cita exitosamente.

	        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	        	
	        	<span aria-hidden="true">&times;</span>

	        </button>

	    </div>
	@endif


	@if (session('info'))
	    <div class="alert alert-info alert-dismissible fade show" role="alert">
	        
	        {{ session('info') }}

	        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	        	
	        	<span aria-hidden="true">&times;</span>

	        </button>

	    </div>
	@endif

	@if (session('warning'))
	    <div class="alert alert-warning alert-dismissible fade show" role="alert">
	        
	        {{ session('warning') }}

	        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	        	
	        	<span aria-hidden="true">&times;</span>

	        </button>

	    </div>
	@endif
	
</div>

resources/views/app/components/back-btn.blade.php
<div class="mb-3">
	<a href="{{ $route }}">
		<i class="fa fa-angle-left mr-1 fa-sm"></i>
		{{$text}}
	</a>
</div>

resources/views/app/components/containers-table.blade.php
<div class="card shadow-sm">
	<div class="card-header d-flex align-items-center">
		<p class="lead m-0">{{ $title }}</p>
	</div>

	@if($containers->total())
		
		<table class="table table-striped m-0">
			
			<thead>
				<tr>
					<th nowrap>Contenedor</th>
					<th nowrap>Descripción</th>
					<th nowrap>Compañía</th>
					<th nowrap>Emisor</th>
					<th nowrap>No. candado</th>
					<th nowrap>No. contenedor</th>
					<th nowrap>No. pedimento</th>
				</tr>
			</thead>

			<tbody>
				
				@foreach($containers as $container)
	
				<tr>
					<td>
						<a href="{{ route('containers.show', $container) }}">
							{{ $container->name }}
						</a>
					</td>
					<td>{{ $container->description }}</td>
					<td>{{ optional($container->date)->company_name }}</td>
					<td>{{ $container->issuing_by }}</td>
					<td>{{ $container->padlock }}</td>
					<td>{{ $container->number }}</td>
					<td>{{ $container->petition }}</td>
				</tr>

				@endforeach

			</tbody>

		</table>

	@else


		<div class="card-body">
			<div class="row">
				<div class="col-sm-4 mx-auto text-center">
					<img src="{{ asset('img/undraw_logistics_x4dc.svg.svg') }}" class="svg_img w-50 mb-4" alt="">
					<p class="lead">No se han agregado contenedores aún.</p>
					<a href="#" class="btn btn-primary">
						<i class="fa fa-plus mr-2"></i> 
						Agrega uno
					</a>
				</div>
			</div>
		</div>


	@endif

	@if($containers->total() > $containers->perPage())

	<div class="card-footer pb-0">
		{{ $containers->links() }}
	</div>

	@endif
</div>

resources/views/app/components/dates-table.blade.php
<div class="card shadow-sm">
	<div class="card-header d-flex align-items-center">
		<p class="lead m-0">{{ $title }}</p>

		<a href="{{ isset($route) ? $route : route('dates.create') }}"
			class="btn btn-primary ml-auto">
			<i class="fa fa-plus mr-2"></i>
			Nueva
		</a>
	</div>
	
	@if($dates->total())

	<div class="table-responsive">
		<table class="table table-striped m-0">
			<thead>
				<tr>
					<th>Compañía</th>
					<th>Visitantes</th>
					<th>Asunto</th>
					<th>Departamento</th>
					<th>Fecha y hora</th>
					<th>Vigencia</th>
					<th>Status</th>
					<th>Detalles</th>
				</tr>
			</thead>

			<tbody>
				@foreach($dates as $date)
				<tr>
					<td>
						<a href="{{ route('companies.show', $date->company_id) }}">
							{{ $date->company_name }}
						</a>
					</td>
					<td nowrap>
						<a href="{{ route('dates.show', $date) }}" 
							data-toggle="tooltip" 
							data-html="true" 
							title="
								@foreach($date->visitors as $visitor)
								<p class='m-0'>{{ $visitor->full_name }}</p>
								@endforeach
							">
							
							{{ $date->visitors_total }}

						</a>
					</td>
					<td>{{ $date->subject }}</td>
					<td>{{ $date->department_name }}</td>
					<td nowrap>{{ $date->start }}</td>
					<td nowrap>{{ $date->end }}</td>
					<td>{!! $date->status_badge !!}</td>
					<td nowrap>
						<a href="{{ route('dates.show', $date) }}">Ver más</a>
					</td>
				</tr>
				@endforeach
			</tbody>
		</table>
	</div>

	@else
	
	<div class="card-body">
		<div class="row">
			<div class="col-sm-4 mx-auto text-center">
				<img src="{{ asset('img/undraw_calendar_dutt.svg') }}" class="svg_img w-50 mb-4" alt="">
				<p class="lead">No se han agregado citas aún.</p>
				<a href="{{ isset($route) ? $route : route('dates.create') }}" class="btn btn-primary">
					<i class="fa fa-plus mr-2"></i> 
					Agrega una
				</a>
			</div>
		</div>
	</div>

	@endif

	@if($dates->total() > $dates->perPage())
	
	<div class="card-footer pb-0">
		
		{{ $dates->links() }}

	</div>

	@endif
</div>

resources/views/app/components/modal.blade.php
<div class="modal fade" id="{{ $id }}" tabindex="-1" role="dialog" aria-labelledby="{{ $id }}Label" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="{{ $id }}Label">{{ $title }}</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
			
				{{ $body }}

			</div>
			<div class="modal-footer">
				{{ $footer }}
			</div>
		</div>
	</div>
</div>

resources/views/app/components/vehicles-table.blade.php
<div class="card shadow-sm">
	<div class="card-header d-flex align-items-center">
		<p class="lead m-0">{{ $title }}</p>
		<a href="{{ isset($route) ? $route : route('new-vehicle') }}" class="btn btn-primary ml-auto">
			<i class="fa fa-plus mr-2"></i>
			Nuevo
		</a>
	</div>
	
	@if($vehicles->total())

	<table class="table table-striped m-0">
		<thead>
			<tr>
				<th>Tipo</th>
				<th>Marca</th>
				<th>Modelo</th>
				<th>Año</th>
				<th>Placas</th>
				<th>Color</th>
				<th>Compañía</th>
				<th>Citas</th>
				<th class="text-right">Detalles</th>
			</tr>
		</thead>

		<tbody>
			@foreach($vehicles as $vehicle)
			<tr>
				<td>{{ $vehicle->type }}</td>
				<td>{{ $vehicle->brand }}</td>
				<td>{{ $vehicle->model }}</td>
				<td>{{ $vehicle->year }}</td>
				<td>{{ $vehicle->plates }}</td>
				<td>{{ $vehicle->color }}</td>
				<td>
					<a href="{{ route('companies.show', $vehicle->company) }}">
						{{ $vehicle->company_name }}
					</a>
				</td>
				<td>{{ $vehicle->dates_total }}</td>
				<td class="text-right">
					<a href="{{ route('companies.vehicles.show', [$vehicle->company, $vehicle]) }}">Ver más</a>
				</td>
			</tr>
			@endforeach
		</tbody>
	</table>

	@else

	<div class="card-body">
		
		<div class="row">
			<div class="col-sm-4 mx-auto text-center">
				<img src="{{ asset('img/undraw_city_driver_jh2h.svg') }}" class="svg_img w-50 mb-4" alt="">
				<p class="lead">No se han agregado vehículos aún.</p>
				<a href="{{ isset($route) ? $route : route('new-vehicle') }}" class="btn btn-primary">
					<i class="fa fa-plus mr-2"></i> 
					Agrega uno
				</a>
			</div>
		</div>

	</div>

	@endif
	
	@if($vehicles->total() > $vehicles->perPage())
	<div class="card-footer pb-0">
		{{ $vehicles->links() }}
	</div>
	@endif
</div>

resources/views/app/components/visitor-actions.blade.php
@if($date_visitor->status_id == 0)

<form action="{{ route('dates.visitors.update', [$date, $date_visitor]) }}" method="post">
	@csrf
	@method('PATCH')
	<input type="hidden" name="status_id" value="1">
	<button class="nowrap btn btn-outline-primary btn-sm">
		<i class="fa fa-calendar-check mr-1"></i>
		LLegando
	</button>
</form>

@elseif($date_visitor->status_id == 1)

<div class="d-flex align-items-center">
	
	<print-label-btn date_id="{{ $date->id }}" date_visitor_id="{{ $date_visitor->id }}"></print-label-btn>

	<form action="{{ route('dates.visitors.update', [$date, $date_visitor]) }}" method="post" class="w-100 mr-2">
		@csrf
		@method('PATCH')
		<input type="hidden" name="status_id" value="2">
		<button class="nowrap btn btn-outline-primary btn-sm btn-block">
			<i class="fa fa-id-card-alt mr-1"></i>
			Ingresar
		</button>
	</form>

</div>

@elseif($date_visitor->status_id == 2)

<div class="d-flex align-items-center">
	
	<form action="{{ route('dates.visitors.update', [$date, $date_visitor]) }}" method="post" class="w-100 mr-2">
		@csrf
		@method('PATCH')
		<input type="hidden" name="status_id" value="3">
		<button class="nowrap btn btn-outline-primary btn-sm btn-block">
			<i class="fa fa-pause-circle mr-1"></i>
			Pausar
		</button>
	</form>

	<form action="{{ route('dates.visitors.update', [$date, $date_visitor]) }}" method="post" class="w-100">
		@csrf
		@method('PATCH')
		<input type="hidden" name="status_id" value="4">
		<button class="nowrap btn btn-outline-danger btn-sm btn-block" onclick="return confirm('¿Estás seguro que deseas finalizar la actividad del visitante?')">
			<i class="fa fa-hourglass-end mr-1"></i>
			Finalizar
		</button>
	</form>

</div>

@elseif($date_visitor->status_id == 3)

<div class="d-flex align-items-center">
	
	<form action="{{ route('dates.visitors.update', [$date, $date_visitor]) }}" method="post" class="w-100 mr-2">
		@csrf
		@method('PATCH')
		<input type="hidden" name="status_id" value="2">
		<button class="nowrap btn btn-outline-primary btn-sm btn-block">
			<i class="fa fa-play-circle mr-1"></i>
			Continuar
		</button>
	</form>

	<form action="{{ route('dates.visitors.update', [$date, $date_visitor]) }}" method="post" class="w-100">
		@csrf
		@method('PATCH')
		<input type="hidden" name="status_id" value="4">
		<button class="nowrap btn btn-outline-danger btn-sm btn-block" onclick="return confirm('¿Estás seguro que deseas finalizar la actividad del visitante?')">
			<i class="fa fa-hourglass-end mr-1"></i>
			Finalizar
		</button>
	</form>

</div>

@elseif($date_visitor->status_id == 4)

<span class="text-danger nowrap"> Cita finalizada </span>

@endif

resources/views/app/components/visitors-table.blade.php
<table class="table table-striped m-0">
	<thead>
		<tr>
			<th>Nombre</th>
			<th>E-mail</th>
			<th>Puesto</th>
			<th>Género</th>
			<th>Tipo</th>
			<th>Compañía</th>
			<th>Total de citas</th>
			<th>Detalles</th>
		</tr>
	</thead>

	<tbody>
		@foreach($visitors as $visitor)
		<tr>
			<td>
				<a href="{{ route('companies.visitors.show', [$visitor->company, $visitor]) }}">
					{{ $visitor->full_name }}
				</a>
			</td>
			<td>{{ $visitor->email }}</td>
			<td>{{ $visitor->jobtitle }}</td>
			<td>{{ $visitor->gender }}</td>
			<td>{{ $visitor->type }}</td>
			<td>
				<a href="{{ route('companies.show', $visitor->company) }}">
					{{ $visitor->company_name }}
				</a>
			</td>
			<td>{{ $visitor->dates_total }}</td>
			<td>
				<a href="{{ route('companies.visitors.show', [$visitor->company, $visitor]) }}">
					Ver más
				</a>
			</td>
		</tr>
		@endforeach
	</tbody>
</table>